name: cloud_9_client
description: An application to book procedures and buy products from cloud 9 clinic.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  flutter_calendar_carousel: ^1.4.12
  table_calendar: ^2.2.3
  provider: ^4.0.4
  http: ^0.12.1
  flutter_launcher_icons: ^0.7.3
  url_launcher: ^5.4.10
  shared_preferences: ^0.5.7+3
  rxdart: ^0.24.1
  image_picker: ^0.6.7+2
  dio: ^3.0.9
  badges: ^1.1.1
  flutter_custom_clippers: ^1.1.1
  random_string: ^2.0.0
  share: ^0.6.4+3
  flutter_country_picker: ^0.1.6
  qr_flutter: ^3.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/cloud9_transparent_logo.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
